config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "users#show"
  resources :users
  resources :dishes
  resources :ingredients
  resources :user_ingredients, only: [:create, :destroy]
  resources :user_dishes, only: [:create, :destroy]
  resources :ingredients_dishes, only: [:create, :destroy, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ingredients_dishes
  has_many :user_dishes
  has_many :ingredients, through: :ingredients_dishes
  has_many :users, through: :user_dishes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # belongs_to :dish
  has_many :ingredients_dishes
  has_many :user_ingredients
  has_many :dishes, through: :ingredients_dishes
  has_many :users, through: :user_ingredients
end

app/models/ingredients_dish.rb
class IngredientsDish < ApplicationRecord
  belongs_to :ingredient
  belongs_to :dish
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_ingredients
  has_many :user_dishes
  has_many :dishes, through: :user_dishes
  has_many :ingredients, through: :user_ingredients
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_dish.rb
class UserDish < ApplicationRecord
  belongs_to :dish
  belongs_to :user
end

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.all
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      redirect_to dishes_path
    else
      redirect_to new_dish_path
    end
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])
    if @dish.update(dish_params)
      redirect_to dish_path(@dish.id)
    else
      redirect_to edit_dish_path(@dish.id)
    end
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.delete
    redirect_to dishes_path
  end


  private

  def dish_params
    params.require(:dish).permit(:name, :description, :course, :cost)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @dishes = Dish.all
    @ingredient = Ingredient.new
  end

  def create
    if (params[:dish_id] == "NONE")
      @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
          redirect_to ingredients_path
        else
          redirect_to new_ingredient_path
        end
    else
      @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
          @new_params = {ingredient_id: @ingredient[:id], dish_id:params[:dish_id].to_i}
          @join = IngredientsDish.create(@new_params)
            redirect_to ingredients_path
        else
          redirect_to new_ingredient_path
        end
    end
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
        redirect_to ingredient_path(@ingredient[:id])
    else
        redirect_to edit_ingredient_path(@ingredient[:id])
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.delete
    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :description)
  end
end

app/controllers/ingredients_dishes_controller.rb
class IngredientsDishesController < ApplicationController
  def new
    p "I am the controller params", params
    @dishes = Dish.all
    @current_ingredient_id = params[:ingredient_id]
    @ingredients_dishes = IngredientsDish.new
  end

  def create
    p "I hit my route successfully", ingredients_dish_params
    @ingredients_dish = IngredientsDish.new(ingredients_dish_params)
    if @ingredients_dish.save
      redirect_to ingredients_path
    else
      redirect_to new_ingredient_path
    end
  end

  def destroy
     new_params = {ingredient_id: params[:ingredient_id][0].to_i, dish_id: params[:dish_id][0].to_i}
     @join = IngredientsDish.find_by(new_params)
     @join.delete
     redirect_to dish_path(new_params[:dish_id])

  end

  private
  def ingredients_dish_params
      params.permit(:ingredient_id, :dish_id)
  end
end

app/controllers/user_dishes_controller.rb
class UserDishesController < ApplicationController
  def create
    new_params = {dish_id: params[:dish_id][0].to_i, user_id: params[:user_id][0].to_i}
    @join = UserDish.create(new_params)
    if @join.save
      redirect_to dishes_path
    else
      redirect_to dishes_path
    end
  end
  def destroy
    new_params = {user_id: current_user[:id], dish_id: params[:id]}
    @join = UserDish.find_by(new_params)
    @join.delete
    redirect_to user_path(current_user.id)
  end

end

app/controllers/user_ingredients_controller.rb
class UserIngredientsController < ApplicationController
  def create
    new_params = {ingredient_id: params[:ingredient_id][0].to_i, user_id: params[:user_id][0].to_i}
    @join = UserIngredient.create(new_params)
    if @join.save
      redirect_to user_path(current_user.id)
    else
      redirect_to user_path(current_user.id)
    end
  end

  def destroy
    new_params = {user_id: current_user[:id], ingredient_id: params[:id]}
    @join = UserIngredient.find_by(new_params)
    @join.delete
    redirect_to user_path(current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      redirect_to new_users_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to edit_user_path(@user.id)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    @user.user_ingredients.each do |instance|
      instance.delete
    end
    @user.user_dishes.each do |instance|
      instance.delete
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/ingredients_dishes_helper.rb
module IngredientsDishesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/user_dishes_controller_helper.rb
module UserDishesControllerHelper
end

app/helpers/user_dishes_helper.rb
module UserDishesHelper
end

app/helpers/user_ingredients_helper.rb
module UserIngredientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/edit.html.erb
<div class="dish-edit-container">
  <div class="form">
    <form action="/dishes/<%= @dish.id %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="hidden" name="_method" value="PUT" />
      <input type="text" name="dish[name]" value="<%= @dish.name %>" />
      <input type="text" name="dish[description]" value="<%= @dish.description %>" />
      <select name="dish[course]">
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
      </select>
      <input type="submit" value="Change this dish!" />
    </form>
  </div>
</div>

app/views/dishes/index.html.erb
<div class="dish-index-container">
  <h1>All Dishes</h1>
  <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Create new dish!</button>".html_safe, new_dish_path %>
  <br>
  <div class="section">
    <div class="dishes-grid">
      <div class="row">
        <% @dishes.each_slice(@dishes.length/2) do |dish| %>
          <div class="col s2 l4 m4 places-holder">
            <% dish.each do |d| %>
              <div class="card hoverable blue-grey lighten-4">
                <h4><%= d.name %></h4>
                <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>More Info</button>".html_safe, dish_path(d.id) %>
                <p><%= d.description %></p>
                <p>Course: <%= d.course %></p>
                <p>Cost  :$<%= d.cost %></p>
                <%= form_tag("/user_dishes", method: "post") do %>
                  <%= hidden_field(:dish_id, "", :value=>d.id )%>
                  <%= hidden_field(:user_id, "", :value=>current_user.id )%>
                  <%= submit_tag( "Add Dish")%>
                <% end %>
                <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Edit</button>".html_safe, edit_dish_path(d.id) %>
                <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Delete</button>".html_safe, dish_path(d.id), method: :delete %>
              </div>
            <% end %>
          </div>
        <% end %>
</div>

app/views/dishes/new.html.erb
<div class="dish-edit-container">
  <div class="form">
    <form method="post" action="/dishes">
      <input type="text" name="dish[name]" placeholder="What is the name of your dish, punk?" />
      <input type="text" name="dish[description]" placeholder="How would you describe this dish?" />
      <select name="dish[course]">
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
      </select>
      <input type="number" name="dish[cost]" placeholder= 42 />
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="submit" value="Create!" />
    </form>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="card blue-grey lighten-4">
  <h2><%= @dish.name %></h2>
  <p><%= @dish.description %></p>
  <p>Course: <%= @dish.course %></p>
  <p>Cost: $<%= @dish.cost %></p>
</div>
<h4>Ingredients:</h4>
<div class="section">
  <div class="ingredients-grid">
    <div class="col s4 l4 m4 places-holder">
      <% @dish.ingredients.each do |ing| %>
        <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>#{ing[:name]}</button>".html_safe, ingredient_path(ing[:id]) %>
        <%= form_tag("/ingredients_dishes/#{ing.id}", method: "delete") do %>
          <%= hidden_field(:ingredient_id, "", :value=>ing.id )%>
          <%= hidden_field(:dish_id, "", :value=>@dish.id )%>
          <%= submit_tag( "Delete #{ing[:name]} from #{@dish.name}")%>
        <%end%>
          <%= form_tag("/user_ingredients", method: "post") do %>
            <%= hidden_field(:ingredient_id, "", :value=>ing.id )%>
            <%= hidden_field(:user_id, "", :value=>current_user.id )%>
            <%= submit_tag("Add Allergy")%>
          <% end %>
          <br>
          <br>
      <% end %>
    </div>
  </div>
</div>
<%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Edit</button>".html_safe, edit_dish_path(@dish.id) %>
<%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Remove</button>".html_safe, dish_path(@dish.id), method: :delete %>

app/views/ingredients/edit.html.erb
<div class="edit-ingredient-container">
  <h1>Edit this ingredient</h1>
  <form action="/ingredients/<%= @ingredient.id %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <input type="hidden" name="_method" value="PUT" />
    <input type="text" name="ingredient[name]" value="<%= @ingredient.name %>" />
    <input type="text" name="ingredient[description]" value="<%= @ingredient.description%>" />
    <input type="submit" value="Change this ingredient!" />
  </form>
</div>

app/views/ingredients/index.html.erb
<h2>List of all the ingredients used in our recipes</h2>
<h4>Select any ingredient to indicate an allergy</h4>
<%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Create a new allergy!</button>".html_safe, new_ingredient_path %>
<br><br>
<div class="section">
  <div class="dishes-grid">
    <div class="row">
      <% @ingredients.each_slice(@ingredients.length/2) do |ingredients| %>
        <div class="col s4 l4 m4 places-holder">
          <% ingredients.each do |ing| %>
            <div class="card hoverable blue-grey lighten-4">
              <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>#{ing[:name]}</button>".html_safe, ingredient_path(ing.id) %><br>
              <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Add to dish</button>".html_safe,
                              :controller=> "ingredients_dishes",
                              :action=> "new",
                              :ingredient_id=>ing[:id] %>
              <%= form_tag("/user_ingredients", method: "post") do %>
                <%= hidden_field(:ingredient_id, "", :value=>ing.id )%>
                <%= hidden_field(:user_id, "", :value=>current_user.id )%>
                <%= submit_tag( "Add Allergy")%>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="ingredient-add-container"
  <h1>Add a new Allergy to our list so that we dont include it!</h1>
  <div class='form'>
    <form method="post" action="/ingredients">
      <input type="text" name="ingredient[name]" placeholder="What is the name of the ingredient?" />
      <input type="text" name="ingredient[description]" placeholder="please give a description so we can be sure to watch out for anything like it!" />
      <select name="dish_id">
        <option value=NONE>None</option>
        <% @dishes.each do |dish| %>
        <option value=<%=dish[:id]%>><%=dish[:name]%></option>
        <% end %>
      </select>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="submit" value="Add Allergy!" />
    </form>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="card blue-grey lighten-4">
  <h2><%= @ingredient[:name] %></h2>
  <p><%=@ingredient[:description] %></p>
</div>
<% if @ingredient.dishes.length > 0 %>
  <h4>All Dishes that include this ingredient</h4>
  <div class="section">
    <div class="ingredients-grid">
      <div class="col s4 l4 m4 places-holder">
        <% @ingredient.dishes.each do |dish| %>
          <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>#{dish[:name]}</button>".html_safe, dish_path(dish[:id]) %><br><br>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <p>Hm, looks like this isn't in anything we currently offer. Lucky you...</p>
  <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Edit</button>".html_safe, edit_ingredient_path(@ingredient.id) %>
  <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Remove</button>".html_safe, ingredient_path(@ingredient.id), method: :delete %>
<% end %>
<br>
<br>
<%= link_to "<button style='width:25%' class='waves-effect waves-light btn'>Back</button>".html_safe, ingredients_path %>

app/views/ingredients_dishes/new.html.erb
<h4>Please Select which Dish to add this to</h4>
<form method="post" action="/ingredients_dishes">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <input type="hidden" name="ingredient_id" value="<%=@current_ingredient_id%>"/>
  <select name="dish_id">
    <% @dishes.each do |dish| %>
      <option value=<%=dish[:id]%>><%=dish[:name]%></option>
    <% end %>
  </select>
  <input type="submit" value="Add it to the dish!" />
</form>

app/views/users/index.html.erb
<% if current_user.auth == 2 %>
  <% @users.each do |user| %>
    <div class="section">
      <div class="users-grid">
        <div class="row">
          <h4>Table: <%=user[:email]%>:</h4>
          <% if user.dishes.length > 0 %>
            <p><%= link_to "<button style='width:50%' class='waves-effect waves-light btn'>Delete order</button>".html_safe, user_path(user[:id]), method: :delete %></p>
            <div class="col s4 l4 m4 places-holder">
              <% user.dishes.each do |dish| %>
                <div class="card hoverable blue-grey lighten-4">
                  <p><%=dish[:name]%></p>
                  <%= link_to "<button style='width:50%' class='waves-effect waves-light btn'>Delete dish</button>".html_safe, user_dish_path(dish.id), method: :delete %><br>
                </div>
              <% end %>
            </div>
          <% else %>
            <p>This table hasn't ordered yet!</p>
          <% end %>

          <% if user.ingredients.length > 0 %>
            <strong>Alergies:</strong>
            <% user.ingredients.each do |ingredient| %>
              <div style='width:50%' class="card hoverable blue-grey lighten-4 right">
                <p><%=ingredient[:name]%></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <% if current_user.dishes.length > 0 %>
    <div class="section">
      <div class="users-grid">
        <div class="row">
          <% current_user.dishes.each do |dish| %>
            <div class="card hoverable blue-grey lighten-4">
              <p><%=dish[:name]%></p>
              <%= link_to "<button style='width:50%' class='waves-effect waves-light btn'>Remove from your order</button>", user_dish_path(dish.id), method: :delete %><br>
            </div>
          <% end %>
        </div>
        <div class="row">
          <% if current_user.ingredients.length > 0 %>
            <strong>Alergies:</strong>
            <% current_user.ingredients.each do |ingredient| %>
              <div style='width:50%' class="card hoverable blue-grey lighten-4 right">
              <p><%=ingredient[:name]%></p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <h4>Get ordering!</h4>
    <% end %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h4><%= @user[:email] %>:</h4>
<%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Add some dishes!</button>".html_safe, dishes_path %>

<div class="section">
  <div class="dishes-grid">
    <div class="row">
      <div class="col s4 l4 m4 places-holder">
        <% if @user.dishes.length > 0 %>
          <% @user.dishes.each do |dish| %>
            <div class="card hoverable blue-grey lighten-4">
              <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>#{dish[:name]}</button>".html_safe, dish_path(dish.id) %>
              <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Delete</button>".html_safe, user_dish_path(dish.id), method: :delete %><br>
            </div>
          <% end %>
        <% else %>
          <% if current_user.auth == 2 %>
            <blockquote><%= @user.email %> haven't ordered anything yet.</blockquote>
          <% else %>
            <blockquote>You haven't ordered yet?</blockquote>
          <% end %>
        <% end %>
      </div>

      <div class="col s4 l4 m4 places-holder">
        <% if @user.ingredients.length > 0 %>
          <strong>Alergies:</strong>
          <% @user.ingredients.each do |ingredient| %>
            <div class="card hoverable blue-grey lighten-4">
              <blockquote><%= ingredient[:name] %></blockquote>
              <%= link_to "<button style='width:100%' class='waves-effect waves-light btn'>Remove</button>".html_safe, user_ingredient_path(ingredient.id), method: :delete %>
            </div>
          <% end %>
        <% else %>
          <% if current_user.auth == 2 %>
            <blockquote><%= @user.email %> doesn't have any allergies at their table.</blockquote>
          <% else %>
            <blockquote>No allergies at your table? That can't be correct...</blockquote>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>